version: '3.8'

services:
  emotion_model_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python app/ai/emotion_model.py